#!/system/bin/sh

start_service() {
    cd /data/adb/JeelsBypasser 
    nohup ./JeelsBoobz 
}

ulimit -SHn 1000000
inotifyd /data/adb/JeelsBypasser/JeelsBoobz.inotify /data/adb/modules/BypassKuroNew &>> /dev/null &
echo -n $! > /data/adb/JeelsBypasser/inotifyd.pid

if [ ! -f /data/adb/modules/JeelsBypasser/disable ] ; then
    start_service
fi
