name: Release Build
on:
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checking version
        id: version
        run: |
          echo ::set-output name=release::$(cat module.prop | grep version= | awk -F'=' '{print $2}')
          echo ::set-output name=releaseCode::$(cat module.prop | grep versionCode= | awk -F'=' '{print $2}')
      - name: Build
        run: zip -r JeelsBypasser_${{ steps.version.outputs.release}}.zip ./ -x '*.git*' -x '*.md' -x '*.json'
      - name: Delete tag ${{ steps.version.outputs.release}} if exists
        uses: dev-drprasad/delete-tag-and-release@v1.0.1
        with:
          delete_release: true
          tag_name: ${{ steps.version.outputs.release}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Tag Release
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ steps.version.outputs.release}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release
        uses: JeelsBoobz/action-gh-release@v3
        if: success()
        with:
          tag_name: ${{ steps.version.outputs.release}}
          files: ./*.zip
          draft: false
          body_path: ./CHANGELOG.md
      - name: Update changelog and Magisk update jsons
        id: update_config
        run: |
          CHANGELOG_URL="https://raw.githubusercontent.com/$GITHUB_REPOSITORY/update/CHANGELOG.md"
          get_update_json() {
            echo -ne "{\n  \"version\": \"${{ steps.version.outputs.release}}\",\n  \"versionCode\": ${{ steps.version.outputs.releaseCode}},\n  \"zipUrl\": \"https://github.com/$GITHUB_REPOSITORY/releases/download/${{ steps.version.outputs.release}}/JeelsBypasser_${{ steps.version.outputs.release}}.zip\",\n  \"changelog\": \"$CHANGELOG_URL\"\n}"
          }
          echo $(get_update_json) > updater.json
      - name: Delete old update branch
        run: git push --delete origin update
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: update
          skip_checkout: true
          file_pattern: CHANGELOG.md *.json
          commit_message: Bump version ${{ steps.version.outputs.release}}